[tool.poetry]
name = "my-package"
version = "0.1.0"
description = ""
authors = ["Your Name"]


[tool.poetry.dependencies]
python = ">=3.10, <4.0"


[tool.poetry.group.dev.dependencies]
autopep8 = "*"


[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
